name: Docker Image Build and Push to ECR to go to K8s env

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  ECR_REPO_ACCOUNT: "559050248035"
  ECR_REPO: "559050248035.dkr.ecr.eu-west-2.amazonaws.com/frontend_ecr_repo"
  REGION: "eu-west-2"
  OIDC_ROLE_ARN: "arn:aws:iam::559050248035:role/OIDCRole"

permissions:
  id-token: write
  contents: read


jobs:
  build_and_push:
    name: Build and Push Docker Image to ECR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: ${{ env.OIDC_ROLE_ARN }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.REGION }}

      - name: STS Get Caller Identity
        run: aws sts get-caller-identity

      - name: Build Docker Image
        id: build
        run: |
          # Create a unique image tag based on the current timestamp
          IMAGE_TAG=$(date +%s)
          echo "Building Docker image with tag $IMAGE_TAG"
          docker build ../ --file Dockerfile --tag youtube-clips-frontend:$IMAGE_TAG
          # Output the tag so it can be used later in this job
          echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Login to ECR
        run: |
          IMAGE_TAG=${{ steps.build.outputs.image_tag }}
          echo "Logging in to ECR with image tag $IMAGE_TAG"
          aws ecr get-login-password --region ${{ env.REGION }} | docker login --username AWS --password-stdin ${{ env.ECR_REPO }}

      - name: Tag and Push Docker Image
        run: |
          IMAGE_TAG=${{ steps.build.outputs.image_tag }}
          echo "Tagging image with $IMAGE_TAG and pushing to ECR"
          docker tag youtube-clips-frontend:$IMAGE_TAG ${{ env.ECR_REPO_ACCOUNT }}.dkr.ecr.eu-west-2.amazonaws.com/frontend_ecr_repo:$IMAGE_TAG
          docker push ${{ env.ECR_REPO_ACCOUNT }}.dkr.ecr.eu-west-2.amazonaws.com/frontend_ecr_repo:$IMAGE_TAG
