name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  ECR_REPO: "438465154544.dkr.ecr.eu-west-2.amazonaws.com/frontend_ecr_repo"
  REGION: "eu-west-2"
  OIDC_ROLE_ARN: "arn:aws:iam::438465154544:role/testingok"


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build ../ --file Dockerfile --tag youtube-clips-frontend:$(date +%s)
  AssumeRoleAndCallIdentity:
    runs-on: ubuntu-latest
    steps:
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: ${{ env.OIDC_ROLE_ARN }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.REGION }}
      - name: Sts GetCallerIdentity
        run: |
          aws sts get-caller-identity




  